language: node_js
node_js:
  - '8'
cache:
  directories:
    - packages/deskpro-messenger/node_modules
    - packages/deskpro-messenger-setup/node_modules
install:
  - yarn
  - yarn bootstrap
script: yarn lerna run build
before_deploy:
  - yarn lerna run build-storybook
  - cd packages/deskpro-messenger/build && zip -r ../../../messenger.zip ./ && cd ../../../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep-history: true
    local-dir: packages/deskpro-messenger/storybook-static
    on:
      branch: master
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: $GITHUB_TOKEN
    file: messenger.zip
    on:
      tags: true
